// frontend/src/types/mindContentTypes.ts

export enum MindContentType {
  ARTICLE = "article",
  VIDEO = "video",
  PODCAST = "podcast",
  BOOK = "book", // Example: Could be expanded
  COURSE = "course", // Example: Could be expanded
  OTHER = "other",
}

export interface MindContentCategory {
  id: number;
  name: string;
  description?: string | null;
  // created_at: string; // Assuming timestamps if present on backend
  // updated_at: string;
}

export interface MindContent {
  id: number;
  title: string;
  description: string;
  url: string;
  content_type: MindContentType;
  category_id: number;
  category?: MindContentCategory; // Optional: For displaying category name directly if joined by backend
  author_name?: string | null;
  read_time_minutes?: number | null; // For articles, books
  duration_minutes?: number | null; // For videos, podcasts
  // user_id?: number; // If content is user-specific or user-suggested
  // is_approved?: boolean; // If there's an approval process
  // created_at: string;
  // updated_at: string;
  // cover_image_url?: string | null;
}

// For creating new mind content (subset of MindContent, ID is generated by backend)
export interface NewMindContentData {
  title: string;
  description: string;
  url: string;
  content_type: MindContentType;
  category_id: number;
  author_name?: string | null;
  read_time_minutes?: number | null;
  duration_minutes?: number | null;
  // cover_image_url?: string | null;
}

// For updating existing mind content (all fields optional)
export type UpdateMindContentData = Partial<NewMindContentData>;
